# Generated by Django 6.0.2 on 2026-02-21 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0006_homework_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال پیام')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reciever', to='teachers.teacher', verbose_name='گیرنده پیام')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sender', to='students.students', verbose_name='فرستنده پیام')),
            ],
        ),
    ]
