# Generated by Django 6.0.2 on 2026-02-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat',
        ),
    ]
