# Generated by Django 6.0.2 on 2026-02-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='number_id',
            field=models.CharField(max_length=10),
        ),
    ]
