# Generated by Django 6.0.2 on 2026-02-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_number_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=35, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=55, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='number_id',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
    ]
