# Generated by Django 6.0.2 on 2026-02-19 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0003_alter_teacher_first_name_alter_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان خبر')),
                ('content', models.TextField(verbose_name='متن خبر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='نویسنده خبر')),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.classes', verbose_name='کلاس مربوطه')),
            ],
        ),
    ]
