# Generated by Django 6.0.2 on 2026-02-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='date',
            field=models.DateField(null=True, verbose_name='تاریخ تحویل تکلیف'),
        ),
    ]
