# Generated by Django 6.0.2 on 2026-02-18 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0003_alter_teacher_first_name_alter_teacher_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان درس')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مدرسه')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس مدرسه')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='معلم')),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان کلاس')),
                ('students', models.ManyToManyField(to='students.students', verbose_name='دانش آموزان کلاس')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.lesson', verbose_name='درس کلاس')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='مدرسه')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.teacher', verbose_name='معلم کلاس')),
            ],
        ),
    ]
