# Generated by Django 6.0.2 on 2026-02-21 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0006_homework_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='home_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_work', to='teachers.homework', verbose_name='تکلیف کلاس'),
        ),
    ]
