# Generated by Django 6.0.2 on 2026-02-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_classes_home_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='home_work',
        ),
    ]
