# Generated by Django 6.0.2 on 2026-02-21 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_classes_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.teacher', verbose_name='معلم کلاس'),
        ),
    ]
